version: "3"

services:
  server:
    build: ./
    environment:
      - DBHOST
      - DBNAME
      - DBUSER
      - DBPASS
      - APIKEY
      - JWTSECRET
      - PORT
      - LOGLEVEL
      - LOGPATH
    network_mode: "host"
    volumes:
      - /home/docker/loyalty-api-logs/:/logs
